### PR TITLE
Suggested (minor) improvements

### PR DESCRIPTION
**Pull request by alexdowad**
I need to test to make sure that everything in index.html still works (though it should). Hope to do that tomorrow.

### CODE REVIEW

**Comment by justinmeiners** [comment]
Hello Alex. Thanks for your improvements! 

I think the comments you added to math portion are helpful. I am wondering if they would fit better in the prose of the lit section, as opposed to comments in code (I don't think this applied to those describing the nelder-mead constants). What do you think?

**Comment by alexdowad** [comment]
@justinmeiners, thanks very much for the response.

I'm not sure where those points on Nelder-Mead would fit well in the existing article. For what it's worth, you have inspired me to write a full blog post of my own with an interactive visualization of Nelder-Mead at work. (I didn't know of the algorithm before reading your article.)

If you feel they would fit well somewhere in the main text, please let me know where and I will be happy to add them.

**Comment by alexdowad** [comment]
Hmm, I've just gone through index.html in a browser and everything looks good. I don't think it actually *executes* the code in math.js or draw.js, though.

Anyways, I believe this PR is ready to merge.

**Comment by justinmeiners** [comment]
@alexdowad thanks again! I did end up moving some content into the prose section of the math.list

> you have inspired me to write a full blog post of my own with an interactive visualization of Nelder-Mead at work

Sounds great! I would be interested in linking off to it in the article, so please let me know when I can look at that.

**Comment by alexdowad** [comment]
Thanks very much, Justin. Will certainly send you a link.

**Comment by alexdowad** [comment]
> > you have inspired me to write a full blog post of my own with an interactive visualization of Nelder-Mead at work
> 
> Sounds great! I would be interested in linking off to it in the article, so please let me know when I can look at that.

The article has been released on my blog:

https://alexdowad.github.io/visualizing-nelder-mead/

Feedback, corrections would be much appreciated.

**Pull request merged**
